{% set name = "clarabel" %}
{% set version = "0.11.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.python.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e7c41c47f0e59aeab99aefff9e58af4a8753ee5269bbeecbd5526fc6f41b9598

build:
  number: 0
  script:
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
  skip: true  # [py<39]

requirements:
  build:
    - python
    - maturin
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
  host:
    - python
    - maturin >=1.0,<2.0
    - pip
  run:
    - python
    - numpy
    - scipy
    - cffi

test:
  files:
    - example_qp.py
    - example_sdp.py
  source_files:
    - python/clarabel/tests
    - examples/data
  imports:
    - clarabel
  commands:
    - pip check
    - python example_qp.py
    - python example_sdp.py
    - python -m pytest python/clarabel/tests -v
  requires:
    - pip
    - pytest
    - numpy
    - scipy
    - python
    - cffi

about:
  home: https://oxfordcontrol.github.io/ClarabelDocs
  license: Apache-2.0
  license_family: Apache
  license_file:
    - LICENSE.md
    - THIRDPARTY.yml
  summary: 'Python interface for Clarabel: Interior Point Conic Optimization Solver'
  description: |
    Clarabel is an interior point numerical solver for convex optimization problems implemented
    in Rust.  It solves linear programs (LPs), quadratic programs (QPs), second-order cone programs 
    (SOCPs) and semidefinite programs (SDPs). It also solves problems with exponential, power
    cone and generalized power cone constraints.
  doc_url: https://oxfordcontrol.github.io/ClarabelDocs
  dev_url: https://github.com/oxfordcontrol/Clarabel.rs

extra:
  recipe-maintainers:
    - goulart-paul
